[project]
name = "geo-darshan"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alpha-bhu",
]

[tool.uv.sources]
alpha-bhu = { path = "/Users/ad/GitHub/alpha-bhu", editable = true }
