[project]
name = "geo-darshan"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gdal>=3.11.3",
    "mercantile>=1.2.1",
    "pyproj>=3.7.2",
    "rasterio>=1.4.3",
]
